name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  tdesign_flutter: ^0.1.0
  cupertino_icons: ^1.0.8
  flutter_displaymode: ^0.6.0
  file_picker: ^8.1.4
  archive: 4.0.7
  xml: ^6.5.0
  process_run: ^1.2.2+1
  path: ^1.9.0
  animated_text_kit: ^4.2.2

  flutter_card_swiper: ^7.0.2
  flutter_swiper_view: ^1.1.8
  uuid: ^4.5.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  extended_text: ^14.2.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  lib: ^0.0.3
  window_manager: ^0.4.3
  fl_chart: ^0.69.2
  flutter_isolate: ^2.1.0
  hive: ^2.2.3
  latext: ^0.4.1
  flex_color_picker: ^3.6.0
  package_info_plus: ^8.1.2
  flutter_tilt: ^3.2.0
  rebirth: ^1.0.2
  page_transition: ^2.2.1
  flutter_markdown: 0.7.6+2
  flutter_markdown_latex: 0.3.4
  markdown: 7.3.0
  video_player: ^2.9.2
  video_player_win: ^3.0.0
  flick_video_player: ^0.9.0
  video_thumbnail: ^0.5.3
  # Added for hotspot attendance feature
  wifi_scan: ^0.4.0+1
  network_info_plus: ^6.1.3
  connectivity_plus: ^5.0.2
  # Added for bluetooth chat feature
  flutter_blue_plus: ^1.31.18
  flutter_ble_peripheral: ^1.1.0
  flutter_math_fork: 0.7.2
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  palette_generator: ^0.3.3+4
  syncfusion_flutter_charts: ^26.1.35
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/chu.png
    - assets/come_on.jpg
    - assets/SourceHanSansCN-Regular.otf