name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  tdesign_flutter: ^0.1.0
  cupertino_icons: ^1.0.8
  flutter_displaymode: ^0.6.0
  file_picker: ^8.1.4
  archive: ^3.6.1
  xml: ^6.5.0
  process_run: ^1.2.2+1
  path: ^1.9.0
  animated_text_kit: ^4.2.2
  yako_theme_switch: ^1.0.0+1
  flutter_card_swiper: ^7.0.2
  liquid_swipe: ^3.1.0
  flutter_swiper_view: ^1.1.8
  uuid: ^4.5.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  extended_text: ^14.2.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  lib: ^0.0.3
  window_manager: ^0.4.3
  fl_chart: ^0.69.2
  flutter_isolate: ^2.1.0
  hive: ^2.2.3
  latext: ^0.4.1
  flex_color_picker: ^3.6.0
  package_info_plus: ^8.1.2
  flutter_tilt: ^3.2.0
  provider: ^4.0.5
  flustars: ^0.2.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  
flutter:
  uses-material-design: true
  assets:
    - bin/wmf2png.exe
    - assets/logo.png
    - assets/chu.png
    - assets/come_on.jpg