name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  tdesign_flutter: ^0.1.0
  cupertino_icons: ^1.0.8
  flutter_displaymode: ^0.6.0
  docx_template: ^0.4.0
  file_picker: ^8.1.4
  archive: ^3.6.1
  xml: ^6.5.0
  process_run: ^1.2.2+1
  path: ^1.9.0
  simple_ripple_animation: ^0.1.0
  animated_text_kit: ^4.2.2
  yako_theme_switch: ^1.0.0+1
  flutter_card_swiper: ^7.0.2
  card_swiper: ^3.0.1
  liquid_swipe: ^3.1.0
  flutter_swiper_view: ^1.1.8
  uuid: ^4.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - bin/wmf2png.exe
    - assets/logo.png
    - assets/chu.png
